# Generated by Django 4.0.3 on 2022-03-10 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=150)),
                ('health_issues', models.CharField(max_length=500)),
                ('weight', models.IntegerField(default=0)),
                ('rabies', models.BooleanField(default=False)),
                ('dhpp', models.BooleanField(default=False)),
                ('bordetella', models.BooleanField(default=False)),
                ('lepto', models.BooleanField(default=False)),
                ('canine_flu', models.BooleanField(default=False)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='main_app.pet')),
            ],
        ),
    ]
