# Generated by Django 4.0.3 on 2022-03-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='health_issues',
            field=models.TextField(max_length=500),
        ),
    ]
